<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class InventoryCategoriesAndItemsSeeder extends Seeder
{
    private function generateCategoryCode(string $name): string
    {
        $words = explode(' ', str_replace('&', '', $name));
        $code = '';
        foreach ($words as $word) {
            if (!empty($word)) {
                $code .= strtoupper(substr($word, 0, 1));
            }
        }
        return $code;
    }

    public function run(): void
    {
        $now = Carbon::now();
        $propertyId = 16; // Tetapkan ID properti untuk item yang akan dibuat

        // 1. Siapkan dan masukkan/update data KATEGORI MASTER
        $categoryNames = [
            'ADAMINISTRASI & GENERAL', 'ENGINEERING', 'OFFICE EQUIPMENT', 'UPS', 'HOUSEKEEPING',
            'ROOM AMENITIES', 'SDB', 'MACHINE', 'STEAM CLEANER', 'OFFICE HOUSEKEEPING',
            'LAUNDRY', 'FORNT OFFICE', 'SALES & MARKEINT', 'KITCHEN TOOLS & EQUIPMENT'
        ];

        foreach ($categoryNames as $name) {
            DB::table('categories')->updateOrInsert(
                ['name' => $name], // Cari berdasarkan nama yang unik
                [
                    'category_code' => $this->generateCategoryCode($name),
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ]
            );
        }

        // 2. Ambil semua kategori master yang ada untuk pemetaan
        $categoryMap = DB::table('categories')->pluck('id', 'name')->toArray();
        $categoryCodeMap = DB::table('categories')->pluck('category_code', 'name')->toArray();
        
        // 3. Hapus data INVENTARIS lama HANYA untuk properti ini
        DB::table('inventories')->where('property_id', $propertyId)->delete();

        // 4. Siapkan data inventaris baru
        $rawItems = [
            ['name' => 'Telephone', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Komputer + ups', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Printer epson', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Printer HP laser jet', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Laptop Asus', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Laptop Toshiba', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Meja kerja', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Lemari file besar', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Lemari file kecil', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Filling Cabinet', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Rak file', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Gantungan Jas', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Kursi hitam besar', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Kursi biru hadap', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Lemari panjang', 'category' => 'ADAMINISTRASI & GENERAL'],
            ['name' => 'Torch light', 'category' => 'ENGINEERING'],
            ['name' => 'rotary hummer 800w', 'category' => 'ENGINEERING'],
            ['name' => 'impact drill 560w', 'category' => 'ENGINEERING'],
            ['name' => 'electronic drill 400w', 'category' => 'ENGINEERING'],
            ['name' => 'hand trolly 100 kg (A)', 'category' => 'ENGINEERING'],
            ['name' => 'hand trolly 100 kg (B)', 'category' => 'ENGINEERING'],
            ['name' => 'welding set/inverter', 'category' => 'ENGINEERING'],
            ['name' => 'manifold ac', 'category' => 'ENGINEERING'],
            ['name' => 'jig saw 570w', 'category' => 'ENGINEERING'],
            ['name' => 'dry wall saw', 'category' => 'ENGINEERING'],
            ['name' => 'bench grinder 8"', 'category' => 'ENGINEERING'],
            ['name' => 'circular saw 1200w', 'category' => 'ENGINEERING'],
            ['name' => 'murble cutter', 'category' => 'ENGINEERING'],
            ['name' => 'electric planner', 'category' => 'ENGINEERING'],
            ['name' => 'bench pipe vise 2.5"', 'category' => 'ENGINEERING'],
            ['name' => 'cutting pipe 4"', 'category' => 'ENGINEERING'],
            ['name' => 'screwdriver set', 'category' => 'ENGINEERING'],
            ['name' => 'precision screwdriver set', 'category' => 'ENGINEERING'],
            ['name' => 'electrician screwdriver set 6pcs', 'category' => 'ENGINEERING'],
            ['name' => 'cristal screwdriver 6.0 mm x 1.5" (+)', 'category' => 'ENGINEERING'],
            ['name' => 'cristal screwdriver 6.0 mm x 1.6" (-)', 'category' => 'ENGINEERING'],
            ['name' => 'screwdriver', 'category' => 'ENGINEERING'],
            ['name' => 'wrenc set', 'category' => 'ENGINEERING'],
            ['name' => 'udjustable wrenc set heavy duty 6"', 'category' => 'ENGINEERING'],
            ['name' => 'udjustable wrenc set heavy duty 8"', 'category' => 'ENGINEERING'],
            ['name' => 'udjustable wrenc set heavy duty 12"', 'category' => 'ENGINEERING'],
            ['name' => 'socket set', 'category' => 'ENGINEERING'],
            ['name' => 'punch & chilsel set', 'category' => 'ENGINEERING'],
            ['name' => 'torx set 9pcs', 'category' => 'ENGINEERING'],
            ['name' => 'kunci L no.1.5-10', 'category' => 'ENGINEERING'],
            ['name' => 'bent nose pliers(tang cucut ) 6"', 'category' => 'ENGINEERING'],
            ['name' => 'lock pliers 7" ( tang betet )', 'category' => 'ENGINEERING'],
            ['name' => 'wire stripping pliers', 'category' => 'ENGINEERING'],
            ['name' => 'kunci pipa 10"', 'category' => 'ENGINEERING'],
            ['name' => 'kunci pipa 12"', 'category' => 'ENGINEERING'],
            ['name' => 'end cutting nippers', 'category' => 'ENGINEERING'],
            ['name' => 'tower pincer', 'category' => 'ENGINEERING'],
            ['name' => 'diagonal cutting pliers', 'category' => 'ENGINEERING'],
            ['name' => 'straight cutting 10"', 'category' => 'ENGINEERING'],
            ['name' => 'pipe cutter & flaring 3/16-5/8', 'category' => 'ENGINEERING'],
            ['name' => 'crimping tool', 'category' => 'ENGINEERING'],
            ['name' => 'crimping tool telephone', 'category' => 'ENGINEERING'],
            ['name' => 'groove joint pliers 10"', 'category' => 'ENGINEERING'],
            ['name' => 'racket &die stock 1/2"-2"', 'category' => 'ENGINEERING'],
            ['name' => 'racket &die stock 31/2"-4"', 'category' => 'ENGINEERING'],
            ['name' => 'vacuum pump 1/2 hp', 'category' => 'ENGINEERING'],
            ['name' => 'vacuum 1200w', 'category' => 'ENGINEERING'],
            ['name' => 'oil can 80cc', 'category' => 'ENGINEERING'],
            ['name' => 'air compressor', 'category' => 'ENGINEERING'],
            ['name' => 'spray gun 1.3mm', 'category' => 'ENGINEERING'],
            ['name' => 'tire inflatorw/ gauge 220 psi', 'category' => 'ENGINEERING'],
            ['name' => 'hot air gun 2000w', 'category' => 'ENGINEERING'],
            ['name' => 'sunction lifter 118mm 150kg', 'category' => 'ENGINEERING'],
            ['name' => 'steel hand riveter', 'category' => 'ENGINEERING'],
            ['name' => 'chissel set ( 4 pcs )', 'category' => 'ENGINEERING'],
            ['name' => 'solder', 'category' => 'ENGINEERING'],
            ['name' => 'desoldering', 'category' => 'ENGINEERING'],
            ['name' => 'measuring tape 7.5 meter', 'category' => 'ENGINEERING'],
            ['name' => 'measuring steel 60cm', 'category' => 'ENGINEERING'],
            ['name' => 'siku 30cm', 'category' => 'ENGINEERING'],
            ['name' => 'water pass 400mm', 'category' => 'ENGINEERING'],
            ['name' => 'roll cable 25 meter', 'category' => 'ENGINEERING'],
            ['name' => 'jet cleaner', 'category' => 'ENGINEERING'],
            ['name' => 'tangga ( small )', 'category' => 'ENGINEERING'],
            ['name' => 'tangga (medium )', 'category' => 'ENGINEERING'],
            ['name' => 'tangga ( long)', 'category' => 'ENGINEERING'],
            ['name' => 'safety belt', 'category' => 'ENGINEERING'],
            ['name' => 'safety eye mask', 'category' => 'ENGINEERING'],
            ['name' => 'safety eye shield', 'category' => 'ENGINEERING'],
            ['name' => 'trek/repair karpet tool', 'category' => 'ENGINEERING'],
            ['name' => 'Heater Pipa PPR', 'category' => 'ENGINEERING'],
            ['name' => 'Kunci Pipa 24"', 'category' => 'ENGINEERING'],
            ['name' => 'Monitor LCD', 'category' => 'OFFICE EQUIPMENT'],
            ['name' => 'CPU computer', 'category' => 'OFFICE EQUIPMENT'],
            ['name' => 'Printer', 'category' => 'UPS'],
            ['name' => 'Water dispencer', 'category' => 'UPS'],
            ['name' => 'Filing cabinet', 'category' => 'UPS'],
            ['name' => 'Work table', 'category' => 'UPS'],
            ['name' => 'work chair', 'category' => 'UPS'],
            ['name' => 'First aid kid box', 'category' => 'UPS'],
            ['name' => 'Linen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bath Towel', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Hand Towel', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bath Mat', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Face towel', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed sheet king', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed sheet queen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed Sheet twin', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow case  small', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow case large', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Cover king', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Cover queen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Cover twin', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed pad king', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed pad queen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed Pad twin', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Insert king', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Insert queen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Duvet Insert twin', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow small', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow large', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Throw pillow/ cushion pillow', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bathrobe', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pool towel', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed skirt king', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed skirt queen', 'category' => 'HOUSEKEEPING'],
            ['name' => 'bed skirt twin', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow protector large', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Pillow protector small', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner twin polos', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner twin batik merah', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner twin batik kuning', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner queen polos', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner queen batik meah', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner queen batik kuning', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner king polos', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner king batik meah', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Bed runner king batik kuning', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Cushion case polos', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Cushion case batik merah', 'category' => 'HOUSEKEEPING'],
            ['name' => 'Cushion case batik kuning', 'category' => 'HOUSEKEEPING'],
            ['name' => 'News paper holder', 'category' => 'ROOM AMENITIES'],
            ['name' => 'Hanger', 'category' => 'ROOM AMENITIES'],
            ['name' => 'Televisi', 'category' => 'SDB'],
            ['name' => 'Tray Coffee set', 'category' => 'SDB'],
            ['name' => 'Cattle jug', 'category' => 'SDB'],
            ['name' => 'Hi ball glass', 'category' => 'SDB'],
            ['name' => 'Cup', 'category' => 'SDB'],
            ['name' => 'Saucer', 'category' => 'SDB'],
            ['name' => 'Spoon', 'category' => 'SDB'],
            ['name' => 'Refrigerator', 'category' => 'SDB'],
            ['name' => 'Table lamp', 'category' => 'SDB'],
            ['name' => 'Tisue towel box', 'category' => 'SDB'],
            ['name' => 'Guest Directory', 'category' => 'SDB'],
            ['name' => 'Chair', 'category' => 'SDB'],
            ['name' => 'Square Sofa', 'category' => 'SDB'],
            ['name' => 'Coffee Table', 'category' => 'SDB'],
            ['name' => 'Standing lamp', 'category' => 'SDB'],
            ['name' => 'Bed side table', 'category' => 'SDB'],
            ['name' => 'Telephone', 'category' => 'SDB'],
            ['name' => 'Remote TV', 'category' => 'SDB'],
            ['name' => 'Alquran', 'category' => 'SDB'],
            ['name' => 'Injil', 'category' => 'SDB'],
            ['name' => 'Yellow pages', 'category' => 'SDB'],
            ['name' => 'Bed side lamp', 'category' => 'SDB'],
            ['name' => 'Alarm Clock', 'category' => 'SDB'],
            ['name' => 'Remote AC', 'category' => 'SDB'],
            ['name' => 'Hair Dryer', 'category' => 'SDB'],
            ['name' => 'Tumbler glass', 'category' => 'SDB'],
            ['name' => 'Tray amenities', 'category' => 'SDB'],
            ['name' => 'Face tisue box', 'category' => 'SDB'],
            ['name' => 'Bottle opener', 'category' => 'SDB'],
            ['name' => 'Wastabin', 'category' => 'SDB'],
            ['name' => 'Astray', 'category' => 'SDB'],
            ['name' => 'Dust Bin Shape', 'category' => 'MACHINE'],
            ['name' => 'Bucket Wringer with 2 Pails, Blue Red', 'category' => 'MACHINE'],
            ['name' => 'Wooden Subvision for KW18-506', 'category' => 'MACHINE'],
            ['name' => 'Deluxe Hotel Serving Cart', 'category' => 'MACHINE'],
            ['name' => 'Cleaning Trolley Grey with Cover', 'category' => 'MACHINE'],
            ['name' => 'Sign Cone, 1170mm, “Wet Floor” Caution', 'category' => 'MACHINE'],
            ['name' => '“Wet Floor” Caution Message', 'category' => 'MACHINE'],
            ['name' => 'Plastic Tool Carrier', 'category' => 'MACHINE'],
            ['name' => 'Mop Head Blue for KW18-02', 'category' => 'MACHINE'],
            ['name' => 'Mop with Handle', 'category' => 'MACHINE'],
            ['name' => 'Draw Tube Extension Handle 6m', 'category' => 'MACHINE'],
            ['name' => 'Glass Scrape Shovel Patch 10” with Handle', 'category' => 'MACHINE'],
            ['name' => 'Glass Scrape Shovel Patch 16” with Handle', 'category' => 'MACHINE'],
            ['name' => 'Glass Scrape Shovel Patch 18” with Handle', 'category' => 'MACHINE'],
            ['name' => 'Waist and Round Shape Duster', 'category' => 'MACHINE'],
            ['name' => 'Spread Water Set 16” with Handle', 'category' => 'MACHINE'],
            ['name' => 'Refill Spread Water Cover 16”', 'category' => 'MACHINE'],
            ['name' => 'Laundry Trolley 920 x 560 x 910 mm', 'category' => 'MACHINE'],
            ['name' => 'Laundry Trolley 1220 x 545 x 1700 mm', 'category' => 'MACHINE'],
            ['name' => 'Dry Vacuum Cleaner 10ℓ', 'category' => 'MACHINE'],
            ['name' => 'Consumer High Pressure Cleaner', 'category' => 'MACHINE'],
            ['name' => 'Spray Extraction', 'category' => 'MACHINE'],
            ['name' => 'Consumer Wet and Dry Vacuum', 'category' => 'MACHINE'],
            ['name' => 'Angle Polisher 5”/125mm, 600W', 'category' => 'MACHINE'],
            ['name' => 'Carpet Blower 900W', 'category' => 'MACHINE'],
            ['name' => 'Key Cabinet', 'category' => 'STEAM CLEANER'],
            ['name' => 'Dustbin Square with Ashtray,', 'category' => 'STEAM CLEANER'],
            ['name' => 'Oval Guest Room Dust Bin, Black 26 x 19 x 27cm', 'category' => 'STEAM CLEANER'],
            ['name' => 'Upright Dust Pan without Broom', 'category' => 'STEAM CLEANER'],
            ['name' => 'Hall Mop L, 36” Deluxe', 'category' => 'STEAM CLEANER'],
            ['name' => 'Hall Mop S, 18” Deluxe', 'category' => 'STEAM CLEANER'],
            ['name' => 'Hall Mop M, 24” Deluxe', 'category' => 'STEAM CLEANER'],
            ['name' => 'Sprayer  500ml (Red,Yellow,Green,Blue)', 'category' => 'STEAM CLEANER'],
            ['name' => 'Cable Reel 1.5mm x 25m', 'category' => 'STEAM CLEANER'],
            ['name' => 'HD Aluminium Step Ladder 6 Steps; 1.83m; 150kg', 'category' => 'STEAM CLEANER'],
            ['name' => 'Aluminium Adjustable Ladder 6.2m, 100kg', 'category' => 'STEAM CLEANER'],
            ['name' => 'Long Srubber', 'category' => 'STEAM CLEANER'],
            ['name' => 'Dusti Cloth', 'category' => 'STEAM CLEANER'],
            ['name' => 'Rubber Scrapper 18” Straight Shape with handle', 'category' => 'STEAM CLEANER'],
            ['name' => 'Glass Cloth', 'category' => 'STEAM CLEANER'],
            ['name' => 'Pedal Dust Bin 30L Biege Body w/ Light grey cover', 'category' => 'STEAM CLEANER'],
            ['name' => 'Plastic dust bin 32 gallon dark grey 120L', 'category' => 'STEAM CLEANER'],
            ['name' => 'Plastic Dust bin 44 gallon dark grey 166L', 'category' => 'STEAM CLEANER'],
            ['name' => 'Dust bin dark grey 120L with pedal & yellow cover', 'category' => 'STEAM CLEANER'],
            ['name' => 'Dust bin dark green 120L with pedal & yellow cover', 'category' => 'STEAM CLEANER'],
            ['name' => 'Dust bin Grey 120L yellow lid', 'category' => 'STEAM CLEANER'],
            ['name' => 'Electrical Cold Water HPC', 'category' => 'STEAM CLEANER'],
            ['name' => 'Ladder', 'category' => 'STEAM CLEANER'],
            ['name' => 'Floor brush with handle "22', 'category' => 'STEAM CLEANER'],
            ['name' => 'Ember gagang', 'category' => 'STEAM CLEANER'],
            ['name' => 'Ordner Besar', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Ordner Kecil', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Clip Board', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Gunting kecil', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'White board Ukuran 120x200', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Key Box', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'komputer', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'meja office', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'telephone', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'kotak p3k', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Printer', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Setrika', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Papan setrika', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Multi plug', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Kursi putar Manager Warna Biru', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Kursi Biru dari besi', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Kursi putar warna hitam', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Kipas angin', 'category' => 'OFFICE HOUSEKEEPING'],
            ['name' => 'Mesin Laundry', 'category' => 'LAUNDRY'],
            ['name' => 'Mesin Pengering', 'category' => 'LAUNDRY'],
            ['name' => 'Strika', 'category' => 'LAUNDRY'],
            ['name' => 'Filling Kabinet', 'category' => 'FORNT OFFICE'],
            ['name' => 'Refrigenerator / Kulkas', 'category' => 'FORNT OFFICE'],
            ['name' => 'Printer Epson', 'category' => 'FORNT OFFICE'],
            ['name' => 'Computer FOM + UPS', 'category' => 'FORNT OFFICE'],
            ['name' => 'Pesawat Telephone', 'category' => 'FORNT OFFICE'],
            ['name' => 'Rak File', 'category' => 'FORNT OFFICE'],
            ['name' => 'Key Rak SDB', 'category' => 'FORNT OFFICE'],
            ['name' => 'Meja', 'category' => 'FORNT OFFICE'],
            ['name' => 'Kursi Abu-abu', 'category' => 'FORNT OFFICE'],
            ['name' => 'Kursi FOM Besar', 'category' => 'FORNT OFFICE'],
            ['name' => 'Brangkas', 'category' => 'FORNT OFFICE'],
            ['name' => 'Bantex File', 'category' => 'FORNT OFFICE'],
            ['name' => 'Charger HT', 'category' => 'FORNT OFFICE'],
            ['name' => 'Printer', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Meja Kerja', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kursi kerja', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kursi banquet', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lemari 2 pintu Besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lemari 2 pintu kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lemari file gantung', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Filling Cabinet', 'category' => 'SALES & MARKEINT'],
            ['name' => 'White board', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Stereoform', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kaca', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Alat Pemotong kertas', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Garbage', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Pesawat Telpon', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dispenser', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Strepler Besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Scan', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Outner', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kamera dan perlengkapan', 'category' => 'SALES & MARKEINT'],
            ['name' => 'I pad', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Laptop', 'category' => 'SALES & MARKEINT'],
            ['name' => 'kitchen asset', 'category' => 'SALES & MARKEINT'],
            ['name' => 'nama barang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'botol sc 1 litter', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Nampan plastik uk kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Nampan plastik uk sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Nampan plastik uk besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Mangkok benin u/ es', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Copper 1 unit', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Blander 1 unit', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Panci kuning', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Cetakan nasi krucut', 'category' => 'SALES & MARKEINT'],
            ['name' => 'alat serut lebar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Alat serut panjang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sendok nasi kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sendok nasi garpu', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sendok nasi besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Penjepit  makanan', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lidle kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sutle kayu', 'category' => 'SALES & MARKEINT'],
            ['name' => 'tevlon untuk telur', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tapper ware bulat', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lidle sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lidle besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Lidle es', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sutle stanlist sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sutle stanlist besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Saringan kecil halus', 'category' => 'SALES & MARKEINT'],
            ['name' => 'keranjang plastik', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Saringan stanlis bulat', 'category' => 'SALES & MARKEINT'],
            ['name' => 'mangkok stanlis', 'category' => 'SALES & MARKEINT'],
            ['name' => 'baskom stanlis kecil dalam', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom stanlis sedang dalam', 'category' => 'SALES & MARKEINT'],
            ['name' => 'baskom stanlis besar dalam', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom stanlis kecil dangkal', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom stanlis sedang dangkal', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom stanlis besar dangkal', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Insert pendek', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Insert mini', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Insert panjang dalam', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Insert panjang dangkal', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang stanlis kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang stanlis sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang stanlis besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang almunium kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang almunium sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Dandang almunium besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Soup stanlis Sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Soup turing', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom plastik kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Baskom plastik sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Plastik kotak kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Plastik kotan sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Plastik kotak besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'mangkok soup', 'category' => 'SALES & MARKEINT'],
            ['name' => 'panci merah kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Pitchere akrilick', 'category' => 'SALES & MARKEINT'],
            ['name' => 'taperware untuk belhotel', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Toples kaca', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Toples plastik', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Toples 25 liter', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Toples 10 litter', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Magicom', 'category' => 'SALES & MARKEINT'],
            ['name' => 'talenan kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Talenan sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Talenan besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Gilingan batu', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tabung gas', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Megicom kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tampah rotan', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tampah plastik merah', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tampah plastik coklat', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Termos nasi besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Termon nasi kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'kompor work', 'category' => 'SALES & MARKEINT'],
            ['name' => 'kompor gas', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kampak(potong daging)', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Pisau kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Pisau sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Pisau buah', 'category' => 'SALES & MARKEINT'],
            ['name' => 'gunting', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Microwafe', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Teflon kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Teflon sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Teflon besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Teflon pemanggang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan baja kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan baja sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan baja besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Showcase 3 pintu 1 unit', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Showcase 2 pintu 1 unit(rusak)', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kulkas 2 pintu 1 unit', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Topes coco crunch', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Toples roti', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kompor fortable', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Keranjang biru', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Keranjang kuning', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Keranjang merah', 'category' => 'SALES & MARKEINT'],
            ['name' => 'piring segi panjang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Piring segi pendek', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Piring kotak', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Piring bulat kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Piring bulat sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Piring bulat besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Gelas acar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Taperware kotak', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan almunium kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan almunium sedang', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Wajan almunium besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Tong sampah', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Sapu', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Serok sampah', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Kain pel', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Serut bulat', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Duble disk kecil', 'category' => 'SALES & MARKEINT'],
            ['name' => 'Duble disk petak', 'category' => 'SALES & MARKEINT'],
            ['name' => 'scuisze', 'category' => 'SALES & MARKEINT'],
            ['name' => 'telenan putih ( buah )', 'category' => 'SALES & MARKEINT'],
            ['name' => 'talenan kayu bulat potong ayam', 'category' => 'SALES & MARKEINT'],
            ['name' => 'saringan halus uk besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'saringan kasar uk besar', 'category' => 'SALES & MARKEINT'],
            ['name' => 'sapu wajan', 'category' => 'SALES & MARKEINT'],
            ['name' => 'mangkok acar & sambal', 'category' => 'SALES & MARKEINT'],
            ['name' => 'sc disk', 'category' => 'SALES & MARKEINT'],
            ['name' => 'tong sampah roda (besar)', 'category' => 'SALES & MARKEINT'],
            ['name' => 'megic com 23-25 liter', 'category' => 'SALES & MARKEINT'],
            ['name' => 'compor 6 bunner', 'category' => 'SALES & MARKEINT'],
            ['name' => 'oven gas lpg ( 2 tingkat )', 'category' => 'SALES & MARKEINT'],
            ['name' => 'work table 2 level ukuran 200 x85x95', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'double sink diswasher ukr 150x85x82', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'worktable chiler ukr 180x70x85 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'work table chiler ukr 130x70x60 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'greas trap', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'solid rak 4 tingkat 1000x500x1550 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'exchaust hood wall type', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'ice machine kecil', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'upright chiller 410 watt', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'upright frezzer 410 watt', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'upright frezzer 250 watt', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'diswaher machine', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'gas range with 4 burner & oven gas', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => '2 burner stove', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'smooth plategridle ( tepanyaki )', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'smooth grill ( steak )', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'chinesewok 2burner & 2 warmer', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'electrik convention oven', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'profer', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'microwave oven', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kompor gas rinnai 2 mata', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'rice cooker winn', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'soup turin( pemanas soup )', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'chavingdish round', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'chavingdish segi empat', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'inset 1/2', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'dispenser hot & cool + galon', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'blender panasonic', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'seperangkat alat komputer', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'meja kantor', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'fail kabinet', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kursi kantor', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'printer hp laserjet', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'mop with handle', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'rbr scrapper 22 inc bend', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'floor brush W/stick red blk 5616', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'bucket wringer31 ltrylw mini one pail', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'storagebox w/wheel 140l org handle', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'tote box gry d', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'deep plate 20.5x55cm light greenglas', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'tinsel garland(7x270cm)grn/red', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'jepitan roti', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kuali baja 20 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kuali baja26 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'bowl deep 16 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'bowl mix 24 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'talenan anti bakteri 2416', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saladtong', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'jepitan gunting', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'golok', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kos spatula', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kuas nilon no 6', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'jepitan kue', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'container', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'sauce pan 16 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kos piring plastik', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'sauce pan18 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'serving tongs 9', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'jepitan st kunci 2011', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'magic comb panasonic 18 ltr', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'panci 30cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'panci 50 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'panci 45 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'pisau dapur 10 prof master', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'pisau dapur 8', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'rosemary frypan 22cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'parutan keju', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saringan dalam gagang kayu 18 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saucepot 16cm estio', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saringan minyak 16 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kocokan telur', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'kos cutting big national', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'stock pot 28 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'baskom fly 40 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang bulat 23cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang bulat 25 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'layer oblong cary rack', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'talenan kayu segi besar35x25 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'mixer hand philips 1530', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'pop uptwister', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'cowekbatu bulat 35 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'uleg batu', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'gunting d-r9s', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saringan minyak yakima 23cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'serok parabola gg kayu 32cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saringan eagle 12 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'cetakan serikaya', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'magic comb yong ma 25000', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'stock pot supra 20qt', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'cetakan agar 0953', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'gelas takar 0,5 ltr', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'saringan minyak miami', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'tempatbumbu 1016', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'tempat bumbu 1018', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'tempat buah 32x11', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'pisau agar agar gg kayu b', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'spatula 5', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'cuting board 40x3,5 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'serokparabola gg kayu 26 cm', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang roti besar', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang roti sedang', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang kue besar', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'loyang kue kecil', 'category' => 'KITCHEN TOOLS & EQUIPMENT'],
            ['name' => 'box donat 50pcs', 'category' => 'KITCHEN TOOLS & EQUIPMENT']
        ];

        $itemsToInsert = [];
        foreach ($rawItems as $it) {
            $catName = $it['category'];
            $catId = $categoryMap[$catName] ?? null;
            
            if ($catId) {
                $catCode = $categoryCodeMap[$catName] ?? 'NULL';
                $randomPart = strtoupper(Str::random(5));
                $itemCode = "{$catCode}-{$randomPart}";

                $itemsToInsert[] = [
                    'item_code'                 => $itemCode,
                    'property_id'               => $propertyId,
                    'name'                      => $it['name'],
                    'category_id'               => $catId,
                    'stock'                     => 0,
                    'unit'                      => 'pcs',
                    'condition'                 => 'baik',
                    'unit_price'                => 0.00,
                    'minimum_standard_quantity' => 0,
                    'purchase_date'             => null,
                    'created_at'                => $now,
                    'updated_at'                => $now,
                ];
            }
        }

        // 5. Masukkan data item baru
        foreach (array_chunk($itemsToInsert, 500) as $chunk) {
            DB::table('inventories')->insert($chunk);
        }
        
        $this->command->info('Master categories ensured and items have been seeded for property ID ' . $propertyId);
    }
}